### ISSUE TITLE
Contact issue

### ISSUE THREAD

**Issue by boshtannik** [CipherDogs/manifest#1]
Hello. As I recognized, some of your team was contacting me. If so - please contact me again to the same contact channel as before. If no new messages will be written by me on that page within two weeks, just close that issue.

**Comment by deadblackclover** [comment]
@boshtannik Hi. There may have been an error, but no one from our team has tried to contact you. It is possible that someone may have introduced themselves as us, but they are definitely not from our team. Be careful

**Comment by boshtannik** [comment]
Got it. Thank you!
